#!/usr/bin/env python3
"""
main.py — VCA Concentration Sweep for CASTEP  v5.1
────────────────────────────────────────────────────
Entry point and run-loop orchestrator.
All physics/I/O is in castep_io.py, all process management in workflow.py,
all user interaction in ui.py.

Usage
─────
  python main.py TiZrC.cell                       # interactive wizard
  python main.py NbMo.cell --species Nb Mo --range 0 1 8
  python main.py TiC.cell  --single               # single compound mode
  python main.py NbMo.cell --resume               # resume last run
  python main.py TiC.cif   --castep-cmd 'castep.serial {seed}'
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import ui
import workflow
from castep_io import read_species, write_vca_cell
from workflow import (
    DONE,
    FAILED,
    PENDING,
    RUNNING,
    SKIPPED,
    ExecResult,
    RunState,
    cmd_is_valid,
    execute_step,
    load_run,
    new_run,
    save_run,
    write_csv,
)

VERSION = "5.2"


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────


def _build_arg_parser():
    import argparse

    parser = argparse.ArgumentParser(
        prog="vca_tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="VCA concentration sweep — CASTEP runner v5.1",
        epilog=(
            "Examples:\n"
            "  python main.py NbMo.cell\n"
            "  python main.py TiZrC.cell --species Ti Zr --range 0 1 8\n"
            "  python main.py TiC.cell --single\n"
            "  python main.py NbMo.cell --resume\n"
            "  python main.py TiC.cif --castep-cmd 'castep.serial {seed}'\n"
        ),
    )
    parser.add_argument("file", type=Path, metavar="STRUCTURE")
    parser.add_argument("--species", nargs=2, metavar=("A", "B"))
    parser.add_argument("--range", nargs=3, metavar=("X0", "X1", "N"))
    parser.add_argument(
        "--single",
        action="store_true",
        help="Single compound mode — run once, no VCA sweep",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume the most recent run in the same folder",
    )
    parser.add_argument(
        "--resume-dir",
        type=Path,
        metavar="DIR",
        help="Resume a specific project folder",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Pause before each step for confirmation",
    )
    parser.add_argument(
        "--keep-all",
        action="store_true",
        help="Keep large output files (.check, .castep_bin, .bands)",
    )
    parser.add_argument("--castep-cmd", dest="castep_cmd", metavar="CMD")
    parser.add_argument(
        "--elastic",
        action="store_true",
        help=(
            "After GeometryOptimization, run finite-strain elastic constants workflow "
            "(strained cells × N + CASTEP SinglePoint + Cij fitting). "
            "Fully built-in — no external scripts required."
        ),
    )
    return parser


def _parse_and_validate_args(parser):
    args = parser.parse_args()

    if not args.file.exists():
        parser.error(f"File not found: '{args.file}'")
    if args.file.suffix.lower() not in {".cif", ".cell"}:
        parser.error(f"Expected .cell or .cif, got '{args.file.suffix}'")

    if args.range is not None:
        try:
            x0 = float(args.range[0])
            x1 = float(args.range[1])
            n_steps = int(args.range[2])

            if not (0.0 <= x0 <= 1.0 and 0.0 <= x1 <= 1.0):
                parser.error("X0 and X1 must be in [0, 1]")
            if n_steps < 1:
                parser.error("N must be ≥ 1")
            args.range = (x0, x1, n_steps)
        except ValueError:
            parser.error("--range needs two floats and one int: X0 X1 N")

    return args


# ─────────────────────────────────────────────────────────────────────────────
# .cell / .cif resolution
# ─────────────────────────────────────────────────────────────────────────────


def _resolve_cell(path: Path) -> Path:
    """Return a .cell file path, converting from .cif via cif2cell if needed."""
    if path.suffix.lower() == ".cell":
        return path

    cell_path = path.with_suffix(".cell")
    if cell_path.exists():
        print(f"  .cell  : {cell_path.name} (found)")
        return cell_path

    if not shutil.which("cif2cell"):
        sys.exit("  ERROR: cif2cell not in PATH — supply a .cell file directly.")

    try:
        subprocess.run(
            ["cif2cell", "-f", str(path), "-p", "castep", "-o", str(cell_path)],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"  .cell  : {cell_path.name} (generated by cif2cell)")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"  ERROR: cif2cell failed:\n{exc.stderr.strip() or 'no output'}")

    return cell_path


# ─────────────────────────────────────────────────────────────────────────────
# Resume logic
# ─────────────────────────────────────────────────────────────────────────────


def _find_latest_run(work_dir: Path, stem: str) -> RunState | None:
    candidates = sorted(
        [d for d in work_dir.iterdir() if d.is_dir() and d.name.startswith(f"{stem}_")],
        key=lambda d: d.stat().st_mtime,
        reverse=True,
    )
    for candidate_dir in candidates:
        state = load_run(candidate_dir)
        if state is not None:
            return state
    return None


def _try_resume(
    work_dir: Path, stem: str, explicit_dir: Path | None
) -> RunState | None:
    if explicit_dir:
        state = load_run(explicit_dir.resolve())
    else:
        state = _find_latest_run(work_dir, stem)

    if state is None:
        return None

    # Crash recovery: reset any steps left in RUNNING state
    for step in state.steps:
        if step.status == RUNNING:
            step.status = PENDING
            step.rc = "interrupted"
            print(f"  ⚠  Step {step.idx:02d} reset (was RUNNING — crash recovery)")

    print(
        f"\n  Found: {state.proj_dir.name}"
        f"  [{state.species_a}(1-x){state.species_b}(x)]"
        f"  {state.n_done} done / {len(state.steps)} total"
    )

    if ui.ask_yes_no("Resume?", default=True):
        save_run(state)
        return state
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────


def _log(log_path: Path, message: str) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with log_path.open("a", encoding="utf-8") as log_file:
        log_file.write(f"[{timestamp}]  {message}\n")


# ─────────────────────────────────────────────────────────────────────────────
# Run loop
# ─────────────────────────────────────────────────────────────────────────────


def _run_loop(
    state: RunState,
    cell_src: Path,
    param_src: Path,
    *,
    interactive: bool,
    keep_all: bool,
) -> None:
    """Main execution loop over all pending steps."""
    steps = state.steps
    total = len(steps)
    log_path = state.proj_dir / "run.log"

    if state.n_pending == 0:
        print("\n  All steps already completed.")
        ui.print_summary(state)
        return

    print(f"\n── {state.n_pending} pending / {total} total")
    if interactive:
        print("  s = skip  q = quit  Ctrl+C = skip current step\n")
    else:
        print("  Ctrl+C = skip current step  |  --interactive to pause between steps\n")

    species_a = state.species_a
    species_b = state.species_b
    # Retrieve vacancy occupancy stored in state (set during wizard if VEC > 8.3)
    _nm_occ = getattr(state, "nonmetal_occupancy", 1.0)

    def _write_cell_for_step(dest: Path, concentration: float) -> None:
        write_vca_cell(
            dest,
            cell_src,
            species_a,
            species_b,
            concentration,
            nonmetal_occupancy=_nm_occ,
        )

    for step in steps:
        if step.status in {DONE, SKIPPED}:
            icon = workflow.STATUS_ICON[step.status]
            conv_marker = (
                "✓"
                if step.geom_converged == "yes"
                else ("⚠" if step.status == DONE else "")
            )
            print(
                f"  {icon} x={step.concentration:.4f}"
                f"  H={step.enthalpy_eV or '—'}"
                f"  a={step.a_opt_ang or '—'}Å"
                f"  {step.wall_time_s or '—'}s"
                f"  {conv_marker}"
            )
            continue

        ui.print_step_header(step, total, state)

        if interactive and state.castep_cmd:
            answer = ui.ask_str("> [Enter] run  /  s skip  /  q quit: ").lower()
            if answer in {"q", "quit"}:
                _log(log_path, f"Step {step.idx:02d}: quit by user")
                print("  Quit. State saved.")
                break
            if answer in {"s", "skip"}:
                step.status = SKIPPED
                step.rc = "user-skip"
                from datetime import datetime as _dt

                now = _dt.now().isoformat(timespec="seconds")
                step.started_at = now
                step.finished_at = now
                save_run(state)
                write_csv(state)
                _log(log_path, f"Step {step.idx:02d}: skipped by user")
                print("  └─ ⊘ Skipped")
                continue

        _log(
            log_path,
            f"Step {step.idx:02d}: START"
            f"  x={step.concentration:.6f}"
            f"  {species_a}={round(1 - step.concentration, 4)}"
            f"  {species_b}={round(step.concentration, 4)}",
        )

        exec_result: ExecResult = execute_step(
            state,
            step,
            cell_src,
            param_src,
            write_cell_fn=_write_cell_for_step,
            keep_all=keep_all,
        )

        ui.print_step_result(
            exec_result=exec_result, step=step, proj_dir=state.proj_dir, seed=state.seed
        )

        status_word = step.status.upper() if not exec_result.skipped else "SKIPPED"
        _log(
            log_path,
            f"Step {step.idx:02d}: {status_word}"
            f"  H={step.enthalpy_eV}"
            f"  a={step.a_opt_ang}"
            f"  t={step.wall_time_s}s"
            f"  conv={step.geom_converged}",
        )
        # Close the step box (elastic sub-step, if scheduled, is appended later)
        if step.status == workflow.DONE and not exec_result.skipped:
            print("  └─ ✓ Step completed.")

    ui.print_summary(state)
    _log(log_path, "Loop finished.")

    # Offer to retry failed steps
    failed_steps = [s for s in steps if s.status == FAILED]
    if failed_steps and state.castep_cmd:
        if ui.ask_yes_no(f"Retry {len(failed_steps)} failed step(s)?", default=False):
            for failed_step in failed_steps:
                failed_step.status = PENDING
            save_run(state)
            _run_loop(
                state, cell_src, param_src, interactive=interactive, keep_all=keep_all
            )


# ─────────────────────────────────────────────────────────────────────────────
# Single compound mode
# ─────────────────────────────────────────────────────────────────────────────


def _run_single_compound(
    state: RunState,
    cell_src: Path,
    param_src: Path,
    keep_all: bool,
) -> None:
    """Run CASTEP once for a single (non-VCA) compound."""
    step = state.steps[0]
    seed = state.seed
    log_path = state.proj_dir / "run.log"

    print(f"\n── Single compound: {seed} ──")

    # write_cell_fn for single mode: just copy the cell verbatim
    def _copy_cell(dest: Path, _concentration: float) -> None:
        import shutil as _shutil

        _shutil.copy2(cell_src, dest)

    _log(log_path, f"Single compound: START  seed={seed}")

    exec_result = execute_step(  # noqa: F841  (result used via step.parsed side-effect)
        state,
        step,
        cell_src,
        param_src,
        write_cell_fn=_copy_cell,
        keep_all=keep_all,
    )

    ui.print_single_result(step, seed)
    status_word = step.status.upper()
    _log(
        log_path,
        f"Single compound: {status_word}"
        f"  H={step.enthalpy_eV}"
        f"  a={step.a_opt_ang}"
        f"  t={step.wall_time_s}s",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────


# ─────────────────────────────────────────────────────────────────────────────
# Finite-strain elastic constants workflow
# ─────────────────────────────────────────────────────────────────────────────


def _run_elastic_workflow(state: RunState, args: object) -> None:
    """
    Run finite-strain elastic constants (Cij) on all DONE steps.

    Smart endpoint handling
    ───────────────────────
    Vegard interpolation requires Cij at x=0 AND x=1 as reference points.
    If the current sweep does not include both endpoints, this function
    checks vca_state.json for existing results and offers to compute any
    missing endpoints automatically before the main sweep begins.
    """
    try:
        from elastic_workflow import (
            interpolate_elastic_vegard,
            run_finite_strain_elastic,
        )
    except ImportError as _e:
        print(f"  ⚠  elastic_workflow.py not importable: {_e}")
        return

    castep_cmd = state.castep_cmd
    if not castep_cmd:
        print("  ⚠  --elastic requires a valid CASTEP command. Skipping.")
        return

    done_steps = [s for s in state.steps if s.status == workflow.DONE]
    n_done = len(done_steps)
    print(
        f"\n── Elastic constants (finite-strain)  {n_done} step(s) ──"
        f"\n   Strained cells generated in-process · CASTEP SinglePoint × N · Cij OLS fit"
        f"\n   VCA intermediate x: Vegard interpolation if CASTEP fails\n"
    )

    # ── Smart endpoint check ──────────────────────────────────────────────────
    # Collect which concentrations are done in this run
    done_concs = {round(s.concentration, 6) for s in done_steps}
    has_x0 = any(c < 1e-5 for c in done_concs)
    has_x1 = any(c > 1.0 - 1e-5 for c in done_concs)

    # If either endpoint is missing, check for a previous run that has it
    def _find_endpoint_elastic(target_x: float) -> dict:
        """Search sibling project dirs for an endpoint Cij result."""
        work_dir = state.proj_dir.parent
        for proj_dir in sorted(work_dir.iterdir()):
            if not proj_dir.is_dir() or proj_dir == state.proj_dir:
                continue
            state_file = proj_dir / "vca_state.json"
            if not state_file.exists():
                continue
            try:
                import json as _json

                data = _json.loads(state_file.read_text())
                if data.get("species_a") != state.species_a:
                    continue
                if data.get("species_b") != state.species_b:
                    continue
                for step_d in data.get("steps", []):
                    conc = step_d.get("concentration", -1)
                    if abs(conc - target_x) < 1e-5 and step_d.get("status") == "done":
                        parsed = step_d.get("parsed", {})
                        if "C11" in parsed:
                            return parsed
            except Exception:
                continue
        return {}

    endpoint_elastic: dict[str, dict] = {}  # "0" or "1" → parsed elastic dict

    missing_endpoints: list[float] = []
    if not has_x0:
        cached = _find_endpoint_elastic(0.0)
        if cached:
            endpoint_elastic["0"] = cached
            print("  │  x=0.0 Cij found in previous run — using cached data.")
        else:
            missing_endpoints.append(0.0)
    if not has_x1:
        cached = _find_endpoint_elastic(1.0)
        if cached:
            endpoint_elastic["1"] = cached
            print("  │  x=1.0 Cij found in previous run — using cached data.")
        else:
            missing_endpoints.append(1.0)

    # Offer to compute missing endpoints interactively
    endpoint_steps_to_run: list[tuple[float, Path]] = []
    if missing_endpoints:
        labels = " and ".join(f"x={v:.1f}" for v in missing_endpoints)
        print(f"  ⚠  Vegard interpolation requires pure endpoints ({labels}).")
        print("     They are missing from the current sweep and all previous runs.")
        try:
            ans = input(f"  Compute {labels} now? [Y/n]: ").strip().lower()
        except EOFError:
            ans = "y"
        if ans in {"", "y", "yes"}:
            import shutil as _shutil

            for ep_x in missing_endpoints:
                ep_dir = state.proj_dir / f"x{ep_x:.4f}_ep"
                ep_dir.mkdir(exist_ok=True)
                # Write the pure endpoint cell + run GeomOpt
                src_cell = state.proj_dir.parent / f"{state.seed}.cell"
                if not src_cell.exists():
                    # Fall back to any .cell in the project dir
                    candidates = list(state.proj_dir.parent.glob("*.cell"))
                    src_cell = candidates[0] if candidates else None
                if src_cell:
                    from castep_io import write_vca_cell

                    ep_cell = ep_dir / f"{state.seed}.cell"
                    write_vca_cell(
                        ep_cell, src_cell, state.species_a, state.species_b, ep_x
                    )
                    ep_param = state.proj_dir.parent / f"{state.seed}.param"
                    if ep_param.exists():
                        _shutil.copy2(ep_param, ep_dir / f"{state.seed}.param")
                    endpoint_steps_to_run.append((ep_x, ep_dir))
                    print(f"  ▶  Queued x={ep_x:.1f} endpoint for GeomOpt + elastic.\n")
                else:
                    print(f"  ✗  Cannot find source .cell — skipping x={ep_x:.1f}")
        else:
            print(
                "  Skipping endpoint computation. "
                "Vegard interpolation will be disabled for intermediate x.\n"
            )

    # Run queued endpoint GeomOpt + elastic first
    import time as _time

    for ep_x, ep_dir in endpoint_steps_to_run:
        x_label = f"x={ep_x:.4f}  (endpoint)"
        print(f"\n  ┌─ {x_label}")
        cmd = castep_cmd.replace("{seed}", state.seed)

        # GeomOpt with the same progress bar used in the main loop
        from castep_io import ACTIVE_ENGINE as _AE
        from workflow import _run_castep_process as _rcp

        _castep_out_ep = ep_dir / f"{state.seed}{_AE.output_suffix}"
        print("  │  ▶ Geometry Optimization …", flush=True)
        _t0_geom = _time.monotonic()
        _geom_res = _rcp(cmd, ep_dir, _castep_out_ep)
        _geom_t = ui._fmt_time(_time.monotonic() - _t0_geom)
        if _geom_res.skipped:
            print("  │  ⊘ GeomOpt skipped")
        else:
            # Parse a_opt from the .castep output for the result line
            try:
                from castep_io import parse_castep_log as _pcl

                _ep_res = _pcl(_castep_out_ep)
                _ep_parsed = _ep_res.to_dict()
                _a_ep = _ep_parsed.get("a_opt_ang", "—")
                _h_ep = _ep_parsed.get("enthalpy_eV", "—")
                print(
                    f"  │  ▶ Geometry Optimization … ✓  ({_geom_t})  [a={_a_ep}Å  H={_h_ep} eV]"
                )
            except Exception:
                print(f"  │  ▶ Geometry Optimization … ✓  ({_geom_t})")
        # Compute VEC + nextra for the endpoint
        try:
            from elasticity import nextra_bands_for, vec_for_concentration

            _vec_ep = vec_for_concentration(
                state.species_a, state.species_b, ep_x, None
            )
            _nextra_ep = nextra_bands_for(ep_x, _vec_ep)
            _n_strains_ep = 6  # cubic default
        except Exception:
            _vec_ep, _nextra_ep, _n_strains_ep = 8.0, 10, 6
        ui.print_elastic_progress(_n_strains_ep, _vec_ep, _nextra_ep)
        _t0_ep = _time.monotonic()
        ep_data = run_finite_strain_elastic(
            seed_dir=ep_dir,
            seed=state.seed,
            castep_cmd=castep_cmd,
            x=ep_x,
            species_a=state.species_a,
            species_b=state.species_b,
            keep_all=getattr(args, "keep_all", False),
            progress_callback=None,
        )
        ui.print_elastic_result(ep_data, _time.monotonic() - _t0_ep)
        key = "0" if ep_x < 0.5 else "1"
        if ep_data and "C11" in ep_data:
            endpoint_elastic[key] = ep_data
        # ui.print_elastic_result already emitted the result line above

    # ── First pass: compute Cij for all steps in the sweep ───────────────────
    elastic_results: dict[float, dict] = {}

    for step in done_steps:
        step_dir = state.proj_dir / step.step_dir
        if not step_dir.exists():
            continue

        x = step.concentration
        x_label = f"x={x:.4f}"
        print(f"\n  ┌─ Elastic  {x_label}")

        # Gather VEC for progress display and adaptive nextra_bands
        _t0_elastic = __import__("time").monotonic()
        try:
            from castep_io import _NONMETALS as _NM_e
            from castep_io import read_species as _rs_e
            from elasticity import (
                generate_strain_steps,
                nextra_bands_for,
                vec_for_concentration,
            )

            _all_sp_e = _rs_e(state.proj_dir.parent / f"{state.seed}.cell")
            _nonmetal_e = next(
                (
                    s
                    for s in _all_sp_e
                    if s.capitalize() in _NM_e
                    and s.capitalize() not in {state.species_a, state.species_b}
                ),
                None,
            )
            _vec_e = vec_for_concentration(
                state.species_a, state.species_b, x, _nonmetal_e
            )
            _nextra_e = nextra_bands_for(x, _vec_e)
            # Count strain steps (cubic = 6)
            from elastic_workflow import _parse_lattice_from_cell as _plc

            _lv = _plc(step_dir / f"{state.seed}.cell")
            _n_strains = len(generate_strain_steps(_lv)) if _lv is not None else 6
        except Exception:
            _vec_e, _nextra_e, _n_strains, _nonmetal_e = 8.0, 15, 6, None
        ui.print_elastic_progress(_n_strains, _vec_e, _nextra_e)

        ep_data = run_finite_strain_elastic(
            seed_dir=step_dir,
            seed=state.seed,
            castep_cmd=castep_cmd,
            x=x,
            species_a=state.species_a,
            species_b=state.species_b,
            nonmetal=_nonmetal_e,
            keep_all=getattr(args, "keep_all", False),
            progress_callback=None,  # silence internal logs; ui handles display
        )
        ui.print_elastic_result(ep_data, __import__("time").monotonic() - _t0_elastic)

        is_failed = not ep_data or "_elastic_error" in ep_data or "C11" not in ep_data
        elastic_results[x] = ep_data if not is_failed else {}

        # Result already printed by ui.print_elastic_result inside the new_run_block
        if not is_failed:
            pass  # success already displayed
        else:
            pass  # failure already displayed

    # ── Collect endpoint Cij for interpolation ────────────────────────────────
    # Priority: this sweep's own results > cached from previous run > endpoint runs
    for x, data in elastic_results.items():
        if abs(x) < 1e-5 and data:
            endpoint_elastic.setdefault("0", data)
        if abs(x - 1.0) < 1e-5 and data:
            endpoint_elastic.setdefault("1", data)

    elastic_at_0 = endpoint_elastic.get("0", {})
    elastic_at_1 = endpoint_elastic.get("1", {})
    have_endpoints = bool(elastic_at_0 and elastic_at_1)

    if not have_endpoints and any(not d for d in elastic_results.values()):
        print(
            "  ⚠  Vegard interpolation skipped: endpoint Cij unavailable.\n"
            "     Run with x=0 and x=1 included, or re-run with the full range.\n"
        )

    # ── Second pass: Vegard interpolation for failed intermediate x ───────────
    for step in done_steps:
        x = step.concentration
        data = elastic_results.get(x, {})

        if data and "C11" in data:
            step.parsed.update(data)
            continue

        if 1e-5 < x < 1.0 - 1e-5 and have_endpoints:
            interp = interpolate_elastic_vegard(x, elastic_at_0, elastic_at_1)
            if interp:
                step.parsed.update(interp)
                b = interp.get("B_Hill_GPa", "—")
                g = interp.get("G_Hill_GPa", "—")
                e = interp.get("E_GPa", "—")
                print(f"  │  x={x:.4f}  Vegard:  B={b}  G={g}  E={e} GPa")
        elif data and "_elastic_error" in data:
            step.parsed.update(data)

    save_run(state)
    csv_path = write_csv(state)
    print(f"\n  Results (with Cij) → {csv_path}\n")


def main() -> None:
    parser = _build_arg_parser()
    args = _parse_and_validate_args(parser)

    print(f"\n  vca_tool v{VERSION}\n")

    src = args.file.resolve()
    work_dir = src.parent
    print(f"  Input : {src}")

    cell_path = _resolve_cell(src)

    # ── Detect mode from cell content ─────────────────────────────────────────
    species_in_cell = read_species(cell_path)
    force_single = getattr(args, "single", False)

    # --species Ti Ti  (or any identical pair) → single compound, no sweep
    cli_species = getattr(args, "species", None)
    same_species_flag = (
        cli_species is not None
        and len(cli_species) == 2
        and cli_species[0].capitalize() == cli_species[1].capitalize()
    )

    # Auto-detect: metal + non-metal in cell without explicit --species → single
    single_mode = force_single or same_species_flag

    if same_species_flag and cli_species:
        print(
            f"\n  │  Both species are identical ({cli_species[0].capitalize()})."
            f"\n     Running Single Compound mode for pure {cli_species[0].capitalize()}.\n"
        )

    # ── Resume attempt ────────────────────────────────────────────────────────
    explicit_resume_dir = getattr(args, "resume_dir", None)
    do_resume = getattr(args, "resume", False) or explicit_resume_dir is not None
    state = _try_resume(work_dir, src.stem, explicit_resume_dir) if do_resume else None

    if state is None:
        # ── New run wizard ────────────────────────────────────────────────────
        param_src = ui.wizard_param(cell_path, species_in_cell, is_vca=not single_mode)
        castep_cmd = ui.wizard_castep_cmd(getattr(args, "castep_cmd", None))

        if single_mode:
            # No species or range needed for single compound.
            if same_species_flag and cli_species:
                species_a = cli_species[0].capitalize()
            else:
                species_a = species_in_cell[0] if species_in_cell else src.stem
            species_b = ""
            c_start, c_end, n_steps = 0.0, 0.0, 1
            nonmetal_occupancy = 1.0  # no vacancy correction for single compound
        else:
            species_a, species_b = ui.wizard_species(
                cell_path, getattr(args, "species", None)
            )

            # Interactive A == B → promote to single mode on the fly
            if species_a == species_b:
                single_mode = True
                species_b = ""
                c_start, c_end, n_steps = 0.0, 0.0, 1
                nonmetal_occupancy = 1.0
            else:
                print(f"\n  System : {species_a}(1-x){species_b}(x)")

                if getattr(args, "range", None):
                    c_start, c_end, n_steps = args.range
                else:
                    print("\n── Concentration range ──")
                    c_start = ui.ask_float("Start [0–1]: ")
                    c_end = ui.ask_float("End   [0–1]: ")
                    n_steps = ui.ask_int("Intervals (e.g. 8): ")

                # ── VEC Stability Predictor ───────────────────────────────────
                from castep_io import _NONMETALS as _NM
                from castep_io import read_species as _read_sp

                all_species = _read_sp(cell_path)
                nonmetals_in_cell = [
                    s
                    for s in all_species
                    if s.capitalize() in _NM
                    and s.capitalize() not in {species_a, species_b}
                ]
                nonmetal = nonmetals_in_cell[0] if nonmetals_in_cell else None
                nonmetal_occupancy = 1.0  # default: no vacancies

                if nonmetal and n_steps > 1:
                    import numpy as _np

                    planned_x = list(
                        _np.linspace(c_start, c_end, n_steps)
                        if n_steps > 1
                        else [c_start]
                    )

                    # Show the full VEC forecast table
                    ui.print_vec_stability_table(
                        species_a, species_b, planned_x, nonmetal
                    )

                    # Guard: ask user about dangerous steps (VEC > 8.4)
                    filtered = ui.ask_vec_guard(
                        species_a,
                        species_b,
                        planned_x,
                        nonmetal,
                        vec_threshold=8.4,
                    )
                    if filtered is not None and len(filtered) < len(planned_x):
                        # User chose to skip red-zone steps.
                        # Recompute n_steps / c_end to the filtered range.
                        if filtered:
                            c_end = max(filtered)
                            n_steps = len(filtered)
                        else:
                            print("  ⚠  All steps would be skipped. Exiting.")
                            sys.exit(0)

        # Timestamped project directory: TiZrC_Mar6_19-08
        timestamp = datetime.now().strftime("%b%-d_%H-%M")
        proj_dir = work_dir / f"{src.stem}_{timestamp}"

        state = new_run(
            seed=src.stem,
            proj_dir=proj_dir,
            species_a=species_a,
            species_b=species_b,
            castep_cmd=castep_cmd,
            c_start=c_start,
            c_end=c_end,
            n_steps=n_steps,
            single_mode=single_mode,
            nonmetal_occupancy=nonmetal_occupancy,
        )
    else:
        # ── Resumed run: re-validate binary ───────────────────────────────────
        if state.castep_cmd:
            binary_part = state.castep_cmd.replace("{seed}", "").strip()
            if not cmd_is_valid(binary_part):
                print("  ⚠  Stored CASTEP command no longer valid.")
                state.castep_cmd = ui.wizard_castep_cmd(None)
                save_run(state)

    param_src = cell_path.with_suffix(".param")

    write_csv(state)
    print(f"\n  Project : {state.proj_dir.name}")
    print("  CSV     : vca_results.csv")
    if not state.castep_cmd:
        print("  Mode    : prepare-only (no CASTEP)")
    print()

    log_path = state.proj_dir / "run.log"
    system_label = (
        f"{state.species_a}(1-x){state.species_b}(x)" if not single_mode else state.seed
    )
    _log(log_path, f"Session start  {system_label}  proj={state.proj_dir.name}")

    if single_mode or state.single_mode:
        _run_single_compound(
            state, cell_path, param_src, keep_all=getattr(args, "keep_all", False)
        )
    else:
        _run_loop(
            state,
            cell_path,
            param_src,
            interactive=getattr(args, "interactive", False),
            keep_all=getattr(args, "keep_all", False),
        )

    _log(log_path, "Session complete.")
    print(f"\n  Results → {state.proj_dir / 'vca_results.csv'}\n")

    # ── Optional: finite-strain elastic constants ─────────────────────────────
    if getattr(args, "elastic", False) and state.n_done > 0:
        _run_elastic_workflow(state, args)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n  Interrupted. State saved.\n")
        sys.exit(0)
