#!/usr/bin/env python3
"""
main.py — VCA Concentration Sweep for CASTEP  v5.1
────────────────────────────────────────────────────
Entry point and run-loop orchestrator.
All physics/I/O is in castep_io.py, all process management in workflow.py,
all user interaction in ui.py.

Usage
─────
  python main.py TiZrC.cell                       # interactive wizard
  python main.py NbMo.cell --species Nb Mo --range 0 1 8
  python main.py TiC.cell  --single               # single compound mode
  python main.py NbMo.cell --resume               # resume last run
  python main.py TiC.cif   --castep-cmd 'castep.serial {seed}'
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import ui
import workflow
from castep_io import read_species, write_vca_cell
from workflow import (
    DONE,
    FAILED,
    PENDING,
    RUNNING,
    SKIPPED,
    ExecResult,
    RunState,
    cmd_is_valid,
    execute_step,
    load_run,
    new_run,
    save_run,
    write_csv,
)

VERSION = "5.1"


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────


def _build_arg_parser():
    import argparse

    parser = argparse.ArgumentParser(
        prog="vca_tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="VCA concentration sweep — CASTEP runner v5.1",
        epilog=(
            "Examples:\n"
            "  python main.py NbMo.cell\n"
            "  python main.py TiZrC.cell --species Ti Zr --range 0 1 8\n"
            "  python main.py TiC.cell --single\n"
            "  python main.py NbMo.cell --resume\n"
            "  python main.py TiC.cif --castep-cmd 'castep.serial {seed}'\n"
        ),
    )
    parser.add_argument("file", type=Path, metavar="STRUCTURE")
    parser.add_argument("--species", nargs=2, metavar=("A", "B"))
    parser.add_argument("--range", nargs=3, metavar=("X0", "X1", "N"))
    parser.add_argument(
        "--single",
        action="store_true",
        help="Single compound mode — run once, no VCA sweep",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume the most recent run in the same folder",
    )
    parser.add_argument(
        "--resume-dir",
        type=Path,
        metavar="DIR",
        help="Resume a specific project folder",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Pause before each step for confirmation",
    )
    parser.add_argument(
        "--keep-all",
        action="store_true",
        help="Keep large output files (.check, .castep_bin, .bands)",
    )
    parser.add_argument("--castep-cmd", dest="castep_cmd", metavar="CMD")
    return parser


def _parse_and_validate_args(parser):
    args = parser.parse_args()

    if not args.file.exists():
        parser.error(f"File not found: '{args.file}'")
    if args.file.suffix.lower() not in {".cif", ".cell"}:
        parser.error(f"Expected .cell or .cif, got '{args.file.suffix}'")

    if args.range is not None:
        try:
            x0 = float(args.range[0])
            x1 = float(args.range[1])
            n_steps = int(args.range[2])
            if not (0.0 <= x0 <= 1.0 and 0.0 <= x1 <= 1.0):
                parser.error("X0 and X1 must be in [0, 1]")
            if n_steps < 1:
                parser.error("N must be ≥ 1")
            args.range = (x0, x1, n_steps)
        except ValueError:
            parser.error("--range needs two floats and one int: X0 X1 N")

    return args


# ─────────────────────────────────────────────────────────────────────────────
# .cell / .cif resolution
# ─────────────────────────────────────────────────────────────────────────────


def _resolve_cell(path: Path) -> Path:
    """Return a .cell file path, converting from .cif via cif2cell if needed."""
    if path.suffix.lower() == ".cell":
        return path

    cell_path = path.with_suffix(".cell")
    if cell_path.exists():
        print(f"  .cell  : {cell_path.name} (found)")
        return cell_path

    if not shutil.which("cif2cell"):
        sys.exit("  ERROR: cif2cell not in PATH — supply a .cell file directly.")

    try:
        subprocess.run(
            ["cif2cell", "-f", str(path), "-p", "castep", "-o", str(cell_path)],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"  .cell  : {cell_path.name} (generated by cif2cell)")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"  ERROR: cif2cell failed:\n{exc.stderr.strip() or 'no output'}")

    return cell_path


# ─────────────────────────────────────────────────────────────────────────────
# Resume logic
# ─────────────────────────────────────────────────────────────────────────────


def _find_latest_run(work_dir: Path, stem: str) -> RunState | None:
    candidates = sorted(
        [d for d in work_dir.iterdir() if d.is_dir() and d.name.startswith(f"{stem}_")],
        key=lambda d: d.stat().st_mtime,
        reverse=True,
    )
    for candidate_dir in candidates:
        state = load_run(candidate_dir)
        if state is not None:
            return state
    return None


def _try_resume(
    work_dir: Path, stem: str, explicit_dir: Path | None
) -> RunState | None:
    if explicit_dir:
        state = load_run(explicit_dir.resolve())
    else:
        state = _find_latest_run(work_dir, stem)

    if state is None:
        return None

    # Crash recovery: reset any steps left in RUNNING state
    for step in state.steps:
        if step.status == RUNNING:
            step.status = PENDING
            step.rc = "interrupted"
            print(f"  ⚠  Step {step.idx:02d} reset (was RUNNING — crash recovery)")

    print(
        f"\n  Found: {state.proj_dir.name}"
        f"  [{state.species_a}(1-x){state.species_b}(x)]"
        f"  {state.n_done} done / {len(state.steps)} total"
    )

    if ui.ask_yes_no("Resume?", default=True):
        save_run(state)
        return state
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────


def _log(log_path: Path, message: str) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with log_path.open("a", encoding="utf-8") as log_file:
        log_file.write(f"[{timestamp}]  {message}\n")


# ─────────────────────────────────────────────────────────────────────────────
# Run loop
# ─────────────────────────────────────────────────────────────────────────────


def _run_loop(
    state: RunState,
    cell_src: Path,
    param_src: Path,
    *,
    interactive: bool,
    keep_all: bool,
) -> None:
    """Main execution loop over all pending steps."""
    steps = state.steps
    total = len(steps)
    log_path = state.proj_dir / "run.log"

    if state.n_pending == 0:
        print("\n  All steps already completed.")
        ui.print_summary(state)
        return

    print(f"\n── {state.n_pending} pending / {total} total")
    if interactive:
        print("  s = skip  q = quit  Ctrl+C = skip current step\n")
    else:
        print("  Ctrl+C = skip current step  |  --interactive to pause between steps\n")

    species_a = state.species_a
    species_b = state.species_b

    def _write_cell_for_step(dest: Path, concentration: float) -> None:
        write_vca_cell(dest, cell_src, species_a, species_b, concentration)

    for step in steps:
        if step.status in {DONE, SKIPPED}:
            icon = workflow.STATUS_ICON[step.status]
            conv_marker = (
                "✓"
                if step.geom_converged == "yes"
                else ("⚠" if step.status == DONE else "")
            )
            print(
                f"  {icon} x={step.concentration:.4f}"
                f"  H={step.enthalpy_eV or '—'}"
                f"  a={step.a_opt_ang or '—'}Å"
                f"  {step.wall_time_s or '—'}s"
                f"  {conv_marker}"
            )
            continue

        ui.print_step_header(step, total, state)

        if interactive and state.castep_cmd:
            answer = ui.ask_str("> [Enter] run  /  s skip  /  q quit: ").lower()
            if answer in {"q", "quit"}:
                _log(log_path, f"Step {step.idx:02d}: quit by user")
                print("  Quit. State saved.")
                break
            if answer in {"s", "skip"}:
                step.status = SKIPPED
                step.rc = "user-skip"
                from datetime import datetime as _dt

                now = _dt.now().isoformat(timespec="seconds")
                step.started_at = now
                step.finished_at = now
                save_run(state)
                write_csv(state)
                _log(log_path, f"Step {step.idx:02d}: skipped by user")
                print("  └─ ⊘ Skipped")
                continue

        _log(
            log_path,
            f"Step {step.idx:02d}: START"
            f"  x={step.concentration:.6f}"
            f"  {species_a}={round(1 - step.concentration, 4)}"
            f"  {species_b}={round(step.concentration, 4)}",
        )

        exec_result: ExecResult = execute_step(
            state,
            step,
            cell_src,
            param_src,
            write_cell_fn=_write_cell_for_step,
            keep_all=keep_all,
        )

        ui.print_step_result(
            exec_result=exec_result, step=step, proj_dir=state.proj_dir, seed=state.seed
        )

        status_word = step.status.upper() if not exec_result.skipped else "SKIPPED"
        _log(
            log_path,
            f"Step {step.idx:02d}: {status_word}"
            f"  H={step.enthalpy_eV}"
            f"  a={step.a_opt_ang}"
            f"  t={step.wall_time_s}s"
            f"  conv={step.geom_converged}",
        )

    ui.print_summary(state)
    _log(log_path, "Loop finished.")

    # Offer to retry failed steps
    failed_steps = [s for s in steps if s.status == FAILED]
    if failed_steps and state.castep_cmd:
        if ui.ask_yes_no(f"Retry {len(failed_steps)} failed step(s)?", default=False):
            for failed_step in failed_steps:
                failed_step.status = PENDING
            save_run(state)
            _run_loop(
                state, cell_src, param_src, interactive=interactive, keep_all=keep_all
            )


# ─────────────────────────────────────────────────────────────────────────────
# Single compound mode
# ─────────────────────────────────────────────────────────────────────────────


def _run_single_compound(
    state: RunState,
    cell_src: Path,
    param_src: Path,
    keep_all: bool,
) -> None:
    """Run CASTEP once for a single (non-VCA) compound."""
    step = state.steps[0]
    seed = state.seed
    log_path = state.proj_dir / "run.log"

    print(f"\n── Single compound: {seed} ──")

    # write_cell_fn for single mode: just copy the cell verbatim
    def _copy_cell(dest: Path, _concentration: float) -> None:
        import shutil as _shutil

        _shutil.copy2(cell_src, dest)

    _log(log_path, f"Single compound: START  seed={seed}")

    exec_result = execute_step(  # noqa: F841  (result used via step.parsed side-effect)
        state,
        step,
        cell_src,
        param_src,
        write_cell_fn=_copy_cell,
        keep_all=keep_all,
    )

    ui.print_single_result(step, seed)
    status_word = step.status.upper()
    _log(
        log_path,
        f"Single compound: {status_word}"
        f"  H={step.enthalpy_eV}"
        f"  a={step.a_opt_ang}"
        f"  t={step.wall_time_s}s",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = _build_arg_parser()
    args = _parse_and_validate_args(parser)

    print(f"\n  vca_tool v{VERSION}\n")

    src = args.file.resolve()
    work_dir = src.parent
    print(f"  Input : {src}")

    cell_path = _resolve_cell(src)

    # ── Detect mode from cell content ─────────────────────────────────────────
    species_in_cell = read_species(cell_path)
    force_single = getattr(args, "single", False)

    # --species Ti Ti  (or any identical pair) → single compound, no sweep
    cli_species = getattr(args, "species", None)
    same_species_flag = (
        cli_species is not None
        and len(cli_species) == 2
        and cli_species[0].capitalize() == cli_species[1].capitalize()
    )

    # Auto-detect: metal + non-metal in cell without explicit --species → single
    single_mode = force_single or same_species_flag

    if same_species_flag and cli_species:
        print(
            f"\n  ℹ  Both species are identical ({cli_species[0].capitalize()})."
            f"\n     Running Single Compound mode for pure {cli_species[0].capitalize()}.\n"
        )

    # ── Resume attempt ────────────────────────────────────────────────────────
    explicit_resume_dir = getattr(args, "resume_dir", None)
    do_resume = getattr(args, "resume", False) or explicit_resume_dir is not None
    state = _try_resume(work_dir, src.stem, explicit_resume_dir) if do_resume else None

    if state is None:
        # ── New run wizard ────────────────────────────────────────────────────
        param_src = ui.wizard_param(cell_path, species_in_cell, is_vca=not single_mode)
        castep_cmd = ui.wizard_castep_cmd(getattr(args, "castep_cmd", None))

        if single_mode:
            # No species or range needed for single compound.
            # If --species Ti Ti was given, use that element; otherwise use
            # the first element found in the cell.
            if same_species_flag and cli_species:
                species_a = cli_species[0].capitalize()
            else:
                species_a = species_in_cell[0] if species_in_cell else src.stem
            species_b = ""
            c_start, c_end, n_steps = 0.0, 0.0, 1
        else:
            species_a, species_b = ui.wizard_species(
                cell_path, getattr(args, "species", None)
            )

            # Interactive A == B → promote to single mode on the fly
            if species_a == species_b:
                single_mode = True
                species_b = ""
                c_start, c_end, n_steps = 0.0, 0.0, 1
            else:
                print(f"\n  System : {species_a}(1-x){species_b}(x)")

                if getattr(args, "range", None):
                    c_start, c_end, n_steps = args.range
                else:
                    print("\n── Concentration range ──")
                    c_start = ui.ask_float("Start [0–1]: ")
                    c_end = ui.ask_float("End   [0–1]: ")
                    n_steps = ui.ask_int("Intervals (e.g. 8): ")

        # Timestamped project directory: TiZrC_Mar6_19-08
        timestamp = datetime.now().strftime("%b%-d_%H-%M")
        proj_dir = work_dir / f"{src.stem}_{timestamp}"

        state = new_run(
            seed=src.stem,
            proj_dir=proj_dir,
            species_a=species_a,
            species_b=species_b,
            castep_cmd=castep_cmd,
            c_start=c_start,
            c_end=c_end,
            n_steps=n_steps,
            single_mode=single_mode,
        )
    else:
        # ── Resumed run: re-validate binary ───────────────────────────────────
        if state.castep_cmd:
            binary_part = state.castep_cmd.replace("{seed}", "").strip()
            if not cmd_is_valid(binary_part):
                print("  ⚠  Stored CASTEP command no longer valid.")
                state.castep_cmd = ui.wizard_castep_cmd(None)
                save_run(state)

    param_src = cell_path.with_suffix(".param")

    write_csv(state)
    print(f"\n  Project : {state.proj_dir.name}")
    print("  CSV     : vca_results.csv")
    if not state.castep_cmd:
        print("  Mode    : prepare-only (no CASTEP)")
    print()

    log_path = state.proj_dir / "run.log"
    system_label = (
        f"{state.species_a}(1-x){state.species_b}(x)" if not single_mode else state.seed
    )
    _log(log_path, f"Session start  {system_label}  proj={state.proj_dir.name}")

    if single_mode or state.single_mode:
        _run_single_compound(
            state, cell_path, param_src, keep_all=getattr(args, "keep_all", False)
        )
    else:
        _run_loop(
            state,
            cell_path,
            param_src,
            interactive=getattr(args, "interactive", False),
            keep_all=getattr(args, "keep_all", False),
        )

    _log(log_path, "Session complete.")
    print(f"\n  Results → {state.proj_dir / 'vca_results.csv'}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n  Interrupted. State saved.\n")
        sys.exit(0)
